#+TITLE: GN1 Features

* Table of Contents                                                     :TOC:
 - [[#online-tour-and-tutorial][Online tour and tutorial]]
 - [[#documentation][Documentation]]
 - [[#search][Search]]
     - [[#species][Species]]
     - [[#group][Group]]
     - [[#data-type][Data type]]
     - [[#data-set][Data set]]
     - [[#get-any][Get any]]
     - [[#combined][Combined]]
     - [[#search-examples][Search examples]]

* Online tour and tutorial

GN1 comes with an online tour and tutorial. The tour gives an example
of selecting data based on a keyword search (a gene name) followed by
selecting expression probes that hits against the gene. Selecting
probes can give statistics, gene ontology type information and also
covariation of expression, correlations between probes and a host of
other functionality (see below).

* Documentation

GN1 comes with an online [[http://www.genenetwork.org/index4.html][user guide]].

A freely downloadable GN1 primer with a focus on exploring the genetic
control and analysis of behavioral variation using powerful online
resources is available from [[http://www.genenetwork.org/images/upload/Williams_Mulligan_Bioinformatics%20of%20Brain%20Short%202012.pdf][INTERNATIONAL REVIEW OF NEUROBIOLOGY]] (Vol
104, p135-158 2012 by Robert W. Williams and Megan K. Mulligan
Bioinformatics of Behavior: Part 2). Despite its specific audience it
is mostly generic. The generalized abstract could be read as:

This chapter provides an introduction into genetic control and
analysis of phenotype variation using powerful online resources. We
introduce you to the new field of systems genetics using case studies
that exploit populations of genetically diverse lines of mice. These
lines differ very widely in patterns of gene and protein expression
and in (classical) phenotypes. We address the following set of related
questions: (1) Can we combine massive genomic data sets with large
aggregates of precise quantitative phenotypical data? (2) Can we map
causal relations between gene variants and phenotypical differences?
(3) Can we simultaneously use these highly coherent data sets to
understand more about the underlying molecular and cellular basis of
these phenotypes.

* Search

When entering the first screen of the website a global search is
presented.

GN1 has a powerful search feature to mine for the experiments that are
included in the large database.

** Species

In the first field select the species. Options include human, model
organisms mouse, rat, Arabidopsis *thaliana* and others (such as
monkey, tomato and barley).

** Group

In the second field select the group information, usually a cross type for model
species or a tissue/experiment for the others.

** Data type

In the third field select the data type. Options include phenotype,
genotype (marker), and for Mouse (for example) a host of neurological
mRNA related data types (expression).

** Data set

In this field experimental sets can be selected for.

** Get any

This is the first search field which can look for simple terms using
wild cards.

** Combined

The combined search field allows for logical AND searches. The
searches allow looking for keywords (diabetes, nicotine), chromosome
locations (QTL, markers, genes, transcripts), GO terms, etc.

It is a bit tricky to find searches that match datasets. But once you
have a working selection it is also printed on the results page: E.g.,
GeneNetwork searched the GE-NIAAA Cerebellum mRNA M430v2 (May05) RMA
Database for all records with MEAN between 1 and 16 and with LRS
between 23 and 46. GeneNetwork found a total of 923 records.

# Note: a missed search leads to a somewhat ungratifying result

# Note: metadata in RDF would allow for creating sophisticated menus

Once you have a selection you can select phenotypes and (for example)
generate a QTL plot on the fly. 

** Search examples

On the main search screen there are some examples, but click the 
link to the [[http://www.genenetwork.org/index4.html][user guide]] to see full examples.

